name: Deployment CD

on:
  workflow_run:
    workflows: ["Docker CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/secondstrap:latest
            docker stop secondstrap-container || true
            docker rm secondstrap-container || true
            docker run -d \
              --name secondstrap-container \
              -p 8000:8000 \
              -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
              -e DEBUG="${{ secrets.DEBUG }}" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e ALLOWED_HOSTS="${{ secrets.ALLOWED_HOSTS }}" \
              -e CLOUDINARY_URL="${{ secrets.CLOUDINARY_URL }}" \
              -e CLOUD_NAME="${{ secrets.CLOUD_NAME }}" \
              -e API_KEY="${{ secrets.API_KEY }}" \
              -e API_SECRET="${{ secrets.API_SECRET }}" \
              -e CLIENT_ID="${{ secrets.CLIENT_ID }}" \
              -e RAZORPAY_KEY_ID="${{ secrets.RAZORPAY_KEY_ID }}" \
              -e RAZORPAY_KEY_SECRET="${{ secrets.RAZORPAY_KEY_SECRET }}" \
              -e RAZORPAY_CALLBACK_URL="${{ secrets.RAZORPAY_CALLBACK_URL }}" \
              -e EMAIL_HOST_USER="${{ secrets.EMAIL_HOST_USER }}" \
              -e EMAIL_HOST_PASSWORD="${{ secrets.EMAIL_HOST_PASSWORD }}" \
              ${{ secrets.DOCKER_USERNAME }}/secondstrap:latest
